version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
  - package-ecosystem: npm
    directory: "/src/main/ui"
    schedule:
      interval: weekly
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
