spring:
  cache:
    cache-names: rooms
    caffeine:
      spec: expireAfterAccess=1h
logging:
  group:
    app: me.itzg.cahweb

management:
  server:
    port: 9090
  endpoint:
    startup:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,startup