
spring:
  cache:
    cache-names: rooms
    caffeine:
      spec: expireAfterAccess=1h
logging:
  group:
    app: me.itzg.cahweb

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health
server:
  port: ${PORT:8080}